services:
  mariadb:
    container_name: mariadb-container
    environment:
      DB_USER: "${MARIADB_USER:?MARIADB_USER environment variable is not set}"
      DB_NAME: "${MARIADB_NAME:?MARIADB_NAME environment variable is not set}"
    build:
      args:
        DB_PORT: "${MARIADB_PORT:?MARIADB_PORT environment variable is not set}"
      context: requirements/mariadb
    image: mariadb:1.0
    volumes:
      - mariadb_vlm:/var/lib/mysql/
    secrets:
      - db_user_pass
      - db_root_pass
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  nginx:
    container_name: nginx-container
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: "${DOMAIN_NAME:?DOMAIN_NAME environment variable is not set}"
        WORDPRESS_PORT: "${WORDPRESS_PORT:?WORDPRESS_PORT environment variable is not set}"
        SERVER_PORT: "${SERVER_PORT:?SERVER_PORT environment variable is not set}"
        PORTAINER_PORT: "${PORTAINER_PORT:?PORTAINER_PORT environment variable is not set}"
        STATIC_WEBSITE_PORT: "${STATIC_WEBSITE_PORT:?STATIC_WEBSITE_PORT environment variable is not set}"
        ADMINER_PORT: "${ADMINER_PORT:?ADMINER_PORT environment variable is not set}"
    image: nginx:1.0
    ports:
      - "${SERVER_PORT:?SERVER_PORT environment variable is not set}:${SERVER_PORT}"
    volumes:
      - wordpress_vlm:/var/www/wordpress/
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy
  
  wordpress:
    container_name: wordpress-container
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME:?DOMAIN_NAME environment variable is not set}"
      DB_USER: "${MARIADB_USER:?MARIADB_USER environment variable is not set}"
      DB_NAME: "${MARIADB_NAME:?MARIADB_NAME environment variable is not set}"
      DB_PORT: "${MARIADB_PORT:?MARIADB_PORT environment variable is not set}"
      WP_ADMIN_USER: "${WP_ADMIN_USER:?WP_ADMIN_USER environment variable is not set}"
      WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL:?WP_ADMIN_EMAIL environment variable is not set}"
      WP_USER: "${WP_USER:?WP_USER environment variable is not set}"
      WP_USER_EMAIL: "${WP_USER_EMAIL:?WP_USER_EMAIL environment variable is not set}"
      WORDPRESS_PORT: "${WORDPRESS_PORT:?WORDPRESS_PORT environment variable is not set}"
    build:
      context: requirements/wordpress
      args:
        WORDPRESS_PORT: "${WORDPRESS_PORT:?WORDPRESS_PORT environment variable is not set}"
    image: wordpress:1.0
    secrets:
      - db_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - wordpress_vlm:/var/www/wordpress
    networks:
      - docker-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      mariadb:
        condition: service_healthy

  portainer:
    container_name: portainer-container
    build:
      context: requirements/bonus/portainer
      args:
        PORTAINER_PORT: "${PORTAINER_PORT:?PORTAINER_PORT environment variable is not set}"
    image: portainer:1.0
    volumes:
      - portainer_vlm:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  adminer:
    container_name: adminer-container
    build:
      context: requirements/bonus/adminer
      args:
        ADMINER_PORT: "${ADMINER_PORT:?ADMINER_PORT environment variable is not set}"
    image: adminer:1.0
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  static_website:
    container_name: static_website-container
    build:
      context: requirements/bonus/static
      args:
        STATIC_WEBSITE_PORT: "${STATIC_WEBSITE_PORT:?STATIC_WEBSITE_PORT environment variable is not set}"
    image: static_website:1.0
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  mariadb_vlm:
    name: "mariadb_vlm"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rabounou/data/mariadb

  wordpress_vlm:
    name: "wordpress_vlm"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rabounou/data/wordpress

  portainer_vlm:
    name: "portainer_vlm"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rabounou/data/portainer

secrets:
  db_user_pass:
    file: ${MARIADB_USER_PASS_FILE:?MARIADB_USER_PASS_FILE environment variable is not set}
  db_root_pass:
    file: ${MARIADB_ROOT_PASS_FILE:?MARIADB_ROOT_PASS_FILE environment variable is not set}
  wp_admin_pass:
    file: ${WP_ADMIN_PASS_FILE:?WP_ADMIN_PASS_FILE environment variable is not set}
  wp_user_pass:
    file: ${WP_USER_PASS_FILE:?WP_USER_PASS_FILE environment variable is not set}

networks:
  docker-network:
    name: docker-network
    driver: bridge