services:
  mariadb:
    container_name: mariadb-container
    environment:
      DB_USER: "${MARIADB_USER}"
      DB_NAME: "${MARIADB_NAME}"
    build:
      args:
        DB_PORT: "${MARIADB_PORT}"
      context: requirements/mariadb
    image: mariadb:1.0
    volumes:
      - mariadb_vlm:/var/lib/mysql/
    ports:
      - "${MARIADB_HPORT}:${MARIADB_PORT}"
    secrets:
      - db_user_pass
      - db_root_pass
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start_period: 30s
    restart: on-failure

  nginx:
    container_name: nginx-container
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: "${DOMAIN_NAME}"
        WORDPRESS_PORT: "${WORDPRESS_PORT}"
        SERVER_PORT: "${SERVER_PORT}"
    image: nginx:1.0
    ports:
      - "443:443"
    volumes:
      - wordpress_vlm:/var/www/wordpress/
    networks:
      - docker-network
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy
  
  wordpress:
    container_name: wordpress-container
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
      DB_USER: "${MARIADB_USER}"
      DB_NAME: "${MARIADB_NAME}"
      DB_PORT: "${MARIADB_PORT}"
      WP_ADMIN_USER: "${WP_ADMIN_USER}"
      WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL}"
      WP_USER: "${WP_USER}"
      WP_USER_EMAIL: "${WP_USER_EMAIL}"
    build:
      context: requirements/wordpress
      args:
        WORDPRESS_PORT: "${WORDPRESS_PORT}"
    image: wordpress:1.0
    ports:
      - "${WORDPRESS_HPORT}:${WORDPRESS_PORT}"
    secrets:
      - db_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - wordpress_vlm:/var/www/wordpress
    networks:
      - docker-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mariadb:
        condition: service_healthy

  # portainer:
  #   container_name: portainer-container
  #   image: portainer/portainer-ce:lts
  #   ports:
  #     - "9443:9443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   networks:
  #     - docker-network
  #   restart: on-failure

  # adminer:
  #   container_name: adminer-container
  #   image: adminer:6
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - docker-network
  #   restart: on-failure

volumes:
  mariadb_vlm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rabounou/data/mariadb

  wordpress_vlm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rabounou/data/wordpress

  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rabounou/data/portainer

secrets:
  db_user_pass:
    file: ${MARIADB_USER_PASS_FILE}
  db_root_pass:
    file: ${MARIADB_ROOT_PASS_FILE}
  wp_admin_pass:
    file: ${WP_ADMIN_PASS_FILE}
  wp_user_pass:
    file: ${WP_USER_PASS_FILE}

networks:
  docker-network:
    driver: bridge
    name: docker-network