events {}

http {
    server {
        listen				${STATIC_WEBSITE_PORT};
        listen				[::]:${STATIC_WEBSITE_PORT};

        root                /var/www/html;
        index               index.html;
}
}