events {}

http {
	server {
		listen				${SERVER_PORT} ssl;
		listen				[::]:${SERVER_PORT} ssl;

		server_name			${DOMAIN_NAME};

		ssl_certificate		/etc/nginx/ssl/inception.crt;
		ssl_certificate_key	/etc/nginx/ssl/inception.key; 

		ssl_protocols		TLSv1.2 TLSv1.3;

		root				/var/www/wordpress;
		index				index.php index.html;

		location /portainer/ {
			proxy_pass http://portainer:${PORTAINER_PORT}/;
		}

		location /static/ {
			proxy_pass http://static_website:${STATIC_WEBSITE_PORT}/;
		}

		location /adminer/ {
			proxy_pass http://adminer:${ADMINER_PORT}/;
		}

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
		    include			fastcgi_params;

		    fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;

		    fastcgi_pass	wordpress:${WORDPRESS_PORT};
		}
	}
}